jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      LUCEE_BUILD_JAVA_VERSION: '17'
      LUCEE_TEST_JAVA_VERSION: '8'
name: Build Java 17, Test Java 8
on:
  repository_dispatch:
    types: trigger-ga___build-java-17-test-8.yml
