jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      LUCEE_BUILD_JAVA_VERSION: '11'
      LUCEE_TEST_JAVA_VERSION: '11'
name: Build with Java 11
on:
  repository_dispatch:
    types: trigger-ga___main-java-11.yml
