jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      LUCEE_BUILD_JAVA_VERSION: '8'
      LUCEE_TEST_JAVA_VERSION: '8'
name: Build with Java 8
on:
  repository_dispatch:
    types: trigger-ga___main-java-8.yml
