jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      LUCEE_BUILD_JAVA_VERSION: '17'
      LUCEE_TEST_JAVA_VERSION: '17'
name: Build with Java 17
on:
  repository_dispatch:
    types: trigger-ga___main-java-17.yml
