jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Build Lucee without using a Maven cache
      run: ant -noinput -buildfile loader/build.xml fast
    - continue-on-error: true
      name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.6'
    - continue-on-error: true
      name: Install Google OSV Scanner
      run: go install github.com/google/osv-scanner/cmd/osv-scanner@v1
    - continue-on-error: true
      name: Run OSV vulnerabilities Scanner
      run: PATH="${PATH}:$(go env GOPATH)/bin" osv-scanner -r ${{ github.workspace
        }}
name: Run OSV Scanner
on:
  repository_dispatch:
    types: trigger-ga___osv-scanner.yml
