jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      LUCEE_BUILD_JAVA_VERSION: '11'
      LUCEE_TEST_JAVA_VERSION: '17'
name: Test with Java 17
on:
  repository_dispatch:
    types: trigger-ga___test-java-17.yml
