jobs:
  build:
    env:
      luceeVersion: zero-6.0.0.495-SNAPSHOT
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v3
      with:
        key: lucee-script-runner-maven-cache
        path: ~/.m2
    - continue-on-error: true
      name: Trigger Lucee Update Providers
      uses: lucee/script-runner@main
      with:
        execute: /update-provider.cfm
        extensionDir: null
        extensions: null
        luceeVersion: ${{ env.luceeVersion }}
        webroot: ${{ github.workspace }}/test
name: Update Provider
on:
  repository_dispatch:
    types: trigger-ga___update-provider.yml
